// ATLAS V4 public-data QA. No network, credentials, or write access.
const fs=require("node:fs"), assert=require("node:assert/strict");
const read=p=>JSON.parse(fs.readFileSync(p,"utf8"));
const projects=read("data/projects.json"), history=read("data/market_history_2006_2026.json"),sources=read("data/source_catalog.json"),metro=read("data/metro_1_schematic.geojson"),planning=read("data/planning_layers.geojson");
const failures=[];const check=(condition,message)=>{if(!condition)failures.push(message)};
const ids=new Set();for(const p of projects){check(!ids.has(p.id),"duplicate project "+p.id);ids.add(p.id);check(typeof p.name==="string"&&p.name.length>0,"project missing name "+p.id);check(typeof p.lat==="number"&&p.lat>9&&p.lat<12&&typeof p.lng==="number"&&p.lng>105&&p.lng<109,"bad project coordinate "+p.id);check(typeof p.coordVerified==="boolean"&&typeof p.priceVerified==="boolean","missing verified flags "+p.id);check(Number.isFinite(p.min)&&Number.isFinite(p.max)&&p.min>=0&&p.max>=p.min,"bad asking price band "+p.id);check(!p.priceVerified||!!p.priceDateVerified,"verified price missing date "+p.id);}
const sourceIds=new Set(sources.records.map(s=>s.id));check(sourceIds.size===sources.records.length,"duplicate source ID");for(const s of sources.records){check(/^https:\/\//.test(s.url),"bad source URL "+s.id);check(!!s.rights_status,"missing source rights "+s.id)}
const obsIds=new Set();for(const o of history.observations){check(!obsIds.has(o.id),"duplicate observation "+o.id);obsIds.add(o.id);check(o.year>=2006&&o.year<=2026,"year out of bounds "+o.id);check(typeof o.source_url==="string"&&/^https:\/\//.test(o.source_url),"missing observation source "+o.id);check(Number.isFinite(o.value)&&o.value>=0,"invalid historical numeric value "+o.id);check(typeof o.metric==="string"&&typeof o.series_id==="string","missing historical methodology label "+o.id);check(typeof o.geography_id==="string","missing geography context "+o.id);check(o.approved_for_public_display===true,"unapproved published observation "+o.id);}
for(const g of [metro,planning]){check(g.type==="FeatureCollection"&&Array.isArray(g.features),"GIS file not FeatureCollection");for(const f of g.features){check(f.type==="Feature"&&!!f.geometry,"invalid GIS feature");}}
check(history.temporal_coverage.baseline_year===2006&&history.temporal_coverage.end_year===2026,"wrong 20-year temporal scope");
const path=require("node:path");const html=fs.readFileSync("history.html","utf8"),map=fs.readFileSync("map-v4.html","utf8");check(html.includes("market_history_2006_2026.json"),"history page points to old dataset");check(map.includes('id="map"')&&map.includes("maplibre"),"map missing");
if(failures.length){console.error("ATLAS DATA QA FAILED\n"+failures.map(x=>"- "+x).join("\n"));process.exit(1)}
console.log("ATLAS DATA QA PASS: "+projects.length+" projects, "+history.observations.length+" observations, "+sourceIds.size+" source records, "+metro.features.length+" schematic metro line(s).");
